spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:file:H:\uni\in-wreclaste\target\data\dev-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  session:
    jdbc:
      initialize-schema: always

server:
  port: 8088
  servlet:
    context-path: /app